#!/bin/bash

# inputs:
# image
# arch
# compiler

# Things that could be paramterized later:
# subdirectory (optional)
# base config
# config fragments/permutations

set -eu
set -o pipefail

image="$1"; shift
arch="$1"; shift
compiler="$1"; shift # "gcc" or "clang"

case "$arch" in
    arm64)
        cross_prefix="aarch64-linux-gnu-"
        ;;
    s390*)
        cross_prefix="s390x-linux-gnu-"
        ;;
    *)
        cross_prefix="${arch}-linux-gnu-"
        ;;
esac

declare -a tc_args
tc_args=()

case "$compiler" in
    gcc)
        tc_args=(CROSS_COMPILE="${cross_prefix}")
    ;;
    clang)
        tc_args=(LLVM=1)
    ;;
    *)
        echo compiler must be 'gcc' or 'clang', got "$compiler"
        exit 1
    ;;
esac

src_path="/src"
config="$src_path/scripts/config"
subdir=drivers/dma/sdxi/

declare -a runc_opts
runc_opts=(
    --interactive
    --log-driver none
    --pids-limit=-1
    --pull=never
    --rm
    --security-opt label=disable
    --volume "$(pwd)":"${src_path}":ro
)

make=(make -k -j"$(nproc)" ARCH="$arch" "${tc_args[@]}")

# FIXME: add CF=-Wsparse-error to C=2 invocations once the remaining
# sparse warnings are addressed.
cat <<EOF |
set -eux

build_path="\$HOME/build"
mkdir "\$build_path"
cd "\$build_path"
${make[@]} -f "$src_path"/Makefile allmodconfig
"$config" -d HEADERS_INSTALL

"$config" -e SDXI
${make[@]} olddefconfig
${make[@]} W=1e C=2 CF=--arch=$arch "$subdir"

"$config" -m SDXI
${make[@]} olddefconfig
${make[@]} W=1e C=2 CF=--arch=$arch "$subdir"

"$config" -d SDXI
${make[@]} olddefconfig
${make[@]} "$subdir"

EOF
podman run "${runc_opts[@]}" "$image"
