#!/bin/bash

set -euo pipefail

################################################################################
#### TAP harness from https://github.com/dnmfarrell/tap.sh/blob/master/tap.sh
################################################################################
TAP_TEST_COUNT=0
TAP_FAIL_COUNT=0

tap_pass() {
	TAP_TEST_COUNT=$((TAP_TEST_COUNT + 1))
	echo "ok $TAP_TEST_COUNT - $1"
}

tap_fail() {
	TAP_TEST_COUNT=$((TAP_TEST_COUNT + 1))
	TAP_FAIL_COUNT=$((TAP_FAIL_COUNT + 1))
	echo "not ok $TAP_TEST_COUNT - $1"
}

tap_end() {
	num_tests="$1"
	[ -z "$num_tests" ] && num_tests="$TAP_TEST_COUNT"
	echo "1..$num_tests"
	[ "$num_tests" = "$TAP_TEST_COUNT" ] || exit 1
	exit $((TAP_FAIL_COUNT > 0)) # C semantics
}

tap_ok() {
	if [ "$1" -eq 0 ]; then
		tap_pass "$2"
	else
		tap_fail "$2"
	fi
}

tap_cmp() {
	if [ "$1" = "$2" ]; then
		tap_pass "$3"
	else
		tap_fail "$3 - expected '$2' but got '$1'"
	fi
}
################################################################################
#### End of TAP harness code
################################################################################

test_exe="$1"

set_sdxi_param() {
    local param="$1"; shift
    local value="$1"; shift

    printf "%s\n" "$value" | \
        sudo tee /sys/module/sdxi/parameters/"$param" >/dev/null
}

# matrix of expected results
# variables:
#   buffer privilege level in PTE, manipulated by PTEditor
#   SDXI driver forces pr bit on for user context akey (hardcoded to 1),
#     meaning that accesses of (say) copy source and destination buffers
#     have the PASID PM bit set in their requests.
#                         pr bit off | pr bit on
# buffer privilege level ==========================
#        user            |    allow   |   allow
#     supervisor         |    deny    |   allow

declare -A expected_results

expected_results=(
    [user,off]="allow"
    [user,on]="allow"
    [supervisor,off]="deny"
    [supervisor,on]="allow"
)

set_sdxi_param "set_pr_bits" "on"

for k in "${!expected_results[@]}" ; do
    privilege="${k%%,*}"
    pr_bit="${k##*,}"
    result="${expected_results[$k]}"
    desc=$(printf "privilege: %10s | pr_bit: %3s | expected result: %5s" \
           "$privilege" "$pr_bit" "$result")

    set_sdxi_param "force_pr_for_user_contexts" "$pr_bit"

    if sudo "$test_exe" --dst="$privilege" --expect="$result" ; then
        tap_pass "$desc"
    else
        tap_fail "$desc"
    fi

done

set_sdxi_param "force_pr_for_user_contexts" "off"

tap_end ${#expected_results[*]}
