obj-$(CONFIG_SDXI) += sdxi.o

sdxi-objs += \
	context.o     \
	device.o      \
	dma.o         \
	error.o       \
	ioctl.o       \
	mmio.o        \
	pci.o         \
	process.o     \
	trace.o       \
	util.o
