name: SDXI driver CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, m68k, x86_64, s390]
        cc: [gcc, clang]
        include:
          - sparse: warn # various known issues on non-x86
          - arch: x86_64
            sparse: fatal
          - cc: clang
            sparse: off # Run sparse on gcc runs only
        exclude:
          - arch: m68k
            cc: clang
    steps:
      - uses: actions/checkout@v4
      - name: Create build environment image
        run: |
          ci-tools/setup buildenv
      - name: Check
        run: |
          ci-tools/sdxi-quick-check --sparse=${{ matrix.sparse }} buildenv ${{ matrix.arch }} ${{ matrix.cc }}
